//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSchoolSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public string GradeID { get; set; }
        public string GradeDesc { get; set; }
    }
}
