//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSchoolSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentScoreReport
    {
        public string StudentScoreReportID { get; set; }
        public string StudentID { get; set; }
        public string SubjectID { get; set; }
        public string GradeID { get; set; }
        public string TeacherID { get; set; }
        public decimal Score { get; set; }
        public int Rank { get; set; }
    }
}
